### PR TITLE
Update to match breaking API change in the pony standard library

### PR DESCRIPTION
**Pull request by ergl**
This change is backwards compatible with ponyc 0.40.0

### CODE REVIEW

**Comment by ergl** [comment]
Actually, since the changes are only done in tests, perhaps this doesn't merit a new release?

**Comment by SeanTAllen** [comment]
There's a release scheduled already

**Comment by SeanTAllen** [comment]
Can you include the why and the what from the RFC as part of the commit comment?

Also implement blah RFC requires someone to go look it up. Better to title it as what the change actually is and link to RFC as part of the largest commit comment.

**Comment by SeanTAllen** [comment]
I think it still needs a release.

**Comment by SeanTAllen** [comment]
Actually you are right, as it is only in a test, no release is needed at this time.

**Comment by ergl** [comment]
Do you want me to revert this and submit another PR without the release notes, or can it stay as it is?

**Comment by SeanTAllen** [comment]
Release notes are fine. It will be released when its released.

**Comment by ergl** [comment]
Just realized that ponyup depends on this and needs to be updated for RFC 69, so maybe we should cut a release.

**Comment by SeanTAllen** [comment]
I think ponyup will be fine as the only change is in a test for appdirs.

**Pull request merged**
