### PR TITLE
add flag for returning unix-style directories on osx.

### LINKED ISSUE #1: macOS option for Unix-style paths
I think it would be a useful option to allow non-GUI apps on macOS to request Unix-style paths instead of macOS desktop paths. Most command-line users on Mac treat it like the Unix that it is, and would not be happy with tool config files down under `~/Library/Application\ Support/` for example.

### PR DESCRIPTION
**Pull request by mfelsche**
closes #1

### CODE REVIEW

**Comment by SeanTAllen** [comment]
I think we should open an issue to change this.

I would much rather:

have 4 primitives:

Mac MacAsUnix, Unix, Windows.

Set that value once. and thread through to where needed. Rather than doing like this.

I do think however that this would be ok for now.

**Review by cquinn — APPROVED** [review]
LGTM

**Comment by mfelsche** [comment]
Rebased to fix conflicts. @SeanTAllen we merge?

**Comment by SeanTAllen** [comment]
@mfelsche yes. if you agree with my reorganization idea, can you open an issue for that?

**Comment by mfelsche** [comment]
I honestly don't 100% understand. Do you want to pass in an argument controlling in which way appdirs are generated? So you could generate unix dirs on windows? I would not go that route.
If you want to switch the current `ifdef` approach that will be mixed with 1 `if` for osx to matching on a primitive in each function, we can totally discuss this, though i like the current approach a little more, but I follow along that this feels cleaner.

**Comment by SeanTAllen** [comment]
I do not like the current approach. I think we should establish in one location what is to be done:

Mac,MacAsUnix, Unix, Windows.

This would be done via a combination of `ifdef` for platform as well as a flag to indicate "as unix". The "as unix" gets ignored everywhere but the Mac. Then, that primitive is supplied to everything rather than doing `ifdef` and `if` in all the locations. match the primitive, do what is correct for that platform.

Currently, you need to do `ifdef osx` and then another `if` for each location. it's easy to mess that up.

Really there are 4 options, but it isn't coded that way. It's coded as 3 options + a variation for Mac that needs to be enforced at each location.

**Pull request merged**
